# ----
# Site

title: The Coder's Kitchen
url: "https://r.eci.pe"
baseurl: ""
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Recipes from the coder's kitchen.
author:
  name: Chris Laundy
  email: chris@laundy.uk
  twitter: chrislaundy
social:
  name: TheKitchenCoder
  links:
    - https://r.eci.pe

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Twitter
  - RSS

_options:
  author_image:
    width: 400
    height: 400

# -------
# Compose
jekyll_compose:
  default_front_matter:
    drafts:
      categories:
      featured_image:
      recipe:
        servings:
        prep:
        cook:
        ingredients_markdown:
        directions_markdown:
    posts:
      categories:
      featured_image:
      recipe:
        servings:
        prep:
        cook:
        ingredients_markdown:
        directions_markdown: